#!/bin/sh
#
# Start Control

umask 077
APPNAME=control
PIDFILE=/var/run/$APPNAME.pid

start() {  
	printf "Starting Control: "
	start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec systemctl > /tmp/system.log
	echo "OK"
}

stop() {
	printf "Stopping Control: "
	if [ -f /var/run/$APPNAME.pid ]; then
		start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	fi
	echo "OK"
}

restart() {     
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
